/* Declarative description of the "Advanced rules" form: group headers and one
   entry per editable rule. Consumed by RuleForm.vue and the store's fill/read. */
export const RULE_FIELDS = [
  { group: "Elimination" },
  { key: "rollover", label: "Rollover — fingers wrap mod base; a hand dies only on exactly base", type: "bool" },
  { key: "base", label: "Base (death threshold, in fraction-units)", type: "int", min: 2, max: 20 },
  { key: "startL", label: "Starting fingers, left hand (in fraction-units)", type: "int", min: 0, max: 19 },
  { key: "startR", label: "Starting fingers, right hand (in fraction-units)", type: "int", min: 0, max: 19 },
  { group: "Number line" },
  { key: "fraction", label: "Fraction — 1 whole, 2 knubs (halves), 4 quarter-knubs (base & start are in these units)", type: "int", min: 1, max: 4 },
  { key: "integers", label: "Integers — hands may go negative/zero; flip a hand to negate it (dies at ±base)", type: "bool" },
  { group: "Splits" },
  { key: "transfers", label: "Transfers (splits between two living hands)", type: "bool" },
  { key: "divisions", label: "Divisions (splits reviving a dead hand)", type: "bool" },
  { key: "suicide", label: "Suicide — a split may kill your own hand", type: "bool" },
  { key: "swaps", label: "Swaps — mirror-swap unequal hands as a turn", type: "bool" },
  { key: "swapsNeedDead", label: "Logan Clause — swaps only trade a dead hand for a live one", type: "bool" },
  { key: "swapLimit", label: "Max consecutive swaps (0 = unlimited)", type: "int", min: 0, max: 20 },
  { key: "passMove", label: "Pass allowed (split to the same distribution)", type: "bool" },
  { key: "evenSplitsOnly", label: "Even splits only", type: "bool" },
  { key: "oddNearEven", label: "…odd totals may split as evenly as possible", type: "bool" },
  { key: "onePointSwitch", label: "One-point switch (0-1 → 1-0, once per game)", type: "bool" },
  { group: "Extra moves" },
  { key: "meta", label: "Meta — combine hands totalling > base, subtract base, redistribute", type: "bool" },
  { key: "selfAttack", label: "Self-attacks allowed", type: "bool" },
  { key: "deathAttack", label: "Death attacks — attacking a dead hand revives it", type: "bool" },
  { key: "selfAdd", label: "Self-adding — may add 1 finger to a living hand", type: "bool" },
  { key: "cherryBomb", label: "Cherry Bomb — exact-base attack kills target, attacker resets to 1", type: "bool" },
  { group: "Winning" },
  { key: "misere", label: "Misère — losing both hands first WINS", type: "bool" },
  { key: "suddenDeath", label: "Sudden death — a total of 1 finger loses", type: "bool" },
  { key: "repetitionDraw", label: "Draw after N-fold repetition (0 = never)", type: "int", min: 0, max: 10 },
];
